name: .NET Desktop Windows CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish WinForms App
        run: dotnet publish source/HotelViewer.Presentation/HotelViewer.Presentation.csproj -c Release -o ./publish

      - name: Build Test
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Zip Artifact
        shell: pwsh
        run: Compress-Archive -Path ./publish/* -DestinationPath ./hotel-viewer-windows-amd64-master.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: hotel-viewer-windows-amd64-master.zip
          name: Release ${{ github.ref_name }}
          body: |
            Автоматический релиз версии ${{ github.ref_name }}
            Все тесты пройдены успешно.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Master Release
        if:   "!startsWith(github.ref, 'refs/tags/')"
        uses: softprops/action-gh-release@v2
        with:
          files: hotel-viewer-windows-amd64-master.zip
          tag_name: master
          name: Build from master
          body: |
            Автоматическая сборка из ветки master.
            Дата обновления: ${{ github.event.head_commit.timestamp }}
            Последний коммит: ${{ github.sha }}
          draft: false
          prerelease: true
          make_latest: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
